services:
  ai-service:
    build: ./ai-service
    container_name: chronos_ai_service
    ports:
      - "8000:8000"
    networks:
      - chronos_network
    restart: always

  backend-service:
    build: ./backend-service
    container_name: chronos_backend_service
    ports:
      - "8080:8080"
    depends_on:
      - ai-service
    environment:
      - AI_SERVICE_URL=http://ai-service:8000
    networks:
      - chronos_network
    restart: always

  frontend-service:
    build: ./frontend-service
    container_name: chronos_frontend_service
    ports:
      - "5173:5173"
    depends_on:
      - backend-service
    networks:
      - chronos_network
    restart: always

networks:
  chronos_network:
    driver: bridge